version: 2
project_name: seq

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - builder: prebuilt

    # When builder is `prebuilt` there are no defaults for goos, goarch,
    # goarm, gomips, goamd64 and targets, so you always have to specify them:
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1

    # prebuilt specific options
    prebuilt:
      # Path must be the template path to the binaries.
      # GoReleaser removes the `dist` directory before running, so you will likely
      # want to put the binaries elsewhere.
      # This field is required when using the `prebuilt` builder.
      path: output/seq_{{ .Os }}_{{ .Arch }}/seq

    # Use 'binary' to set the final name of your binary.
    # This is the name that will be used in archives et al.
    binary: seq

archives:
  - id: seq-archive
    ids:
      - linux
      - darwin
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - config/**/*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: "Features"
      regexp: "^feat"
      order: 0
    - title: "Bug fixes"
      regexp: "^fix"
      order: 1
    - title: "Others"
      order: 999

# Release configuration
release:
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
  header: |
    ## seq {{ .Version }}

    A powerful sequencer with Lua scripting support and MIDI capabilities.

    ### Platform Support
    - **Linux**: Built with Docker for maximum compatibility
    - **macOS**: Native builds for both Intel (amd64) and Apple Silicon (arm64)

  footer: |
    ## Installation

    Download the appropriate binary for your platform from the assets above.

    ### Linux
    ```bash
    curl -L -o seq https://github.com/$GITHUB_REPOSITORY/releases/download/{{ .Version }}/seq_{{ .Version }}_Linux_x86_64.tar.gz
    tar -xzf seq_{{ .Version }}_Linux_x86_64.tar.gz
    chmod +x seq
    ```

    ### macOS
    ```bash
    # For Intel Macs
    curl -L -o seq https://github.com/$GITHUB_REPOSITORY/releases/download/{{ .Version }}/seq_{{ .Version }}_Darwin_x86_64.tar.gz

    # For Apple Silicon Macs
    curl -L -o seq https://github.com/$GITHUB_REPOSITORY/releases/download/{{ .Version }}/seq_{{ .Version }}_Darwin_arm64.tar.gz
    ```

