version: 2
project_name: seq

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    binary: seq
    goos: [linux]
    goarch: [amd64]
    skip: true  # Skip building, use pre-built

  - id: darwin
    binary: seq
    goos: [darwin]
    goarch: [amd64, arm64]
    skip: true  # Skip building, use pre-built

archives:
  - id: default
    builds:
      - linux
      - darwin
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - config/**/*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: "Features"
      regexp: "^feat"
      order: 0
    - title: "Bug fixes"
      regexp: "^fix"
      order: 1
    - title: "Others"
      order: 999

# Release configuration
release:
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
  header: |
    ## seq {{ .Version }}

    A powerful sequencer with Lua scripting support and MIDI capabilities.

    ### Platform Support
    - **Linux**: Built with Docker for maximum compatibility
    - **macOS**: Native builds for both Intel (amd64) and Apple Silicon (arm64)

  footer: |
    ## Installation

    Download the appropriate binary for your platform from the assets above.

    ### Linux
    ```bash
    curl -L -o seq https://github.com/${{ github.repository }}/releases/download/{{ .Version }}/seq_{{ .Version }}_Linux_x86_64.tar.gz
    tar -xzf seq_{{ .Version }}_Linux_x86_64.tar.gz
    chmod +x seq
    ```

    ### macOS
    ```bash
    # For Intel Macs
    curl -L -o seq https://github.com/${{ github.repository }}/releases/download/{{ .Version }}/seq_{{ .Version }}_Darwin_x86_64.tar.gz

    # For Apple Silicon Macs
    curl -L -o seq https://github.com/${{ github.repository }}/releases/download/{{ .Version }}/seq_{{ .Version }}_Darwin_arm64.tar.gz
    ```

